<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AnoCore.Abstractions\AnoCore.Abstractions.csproj" />
    <ProjectReference Include="..\AnoCore.Runtime\AnoCore.Runtime.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.Tournament\AnoCore.Modules.Tournament.csproj" />
  </ItemGroup>
</Project>
