<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnoCore.TestModuleFixture\AnoCore.TestModuleFixture.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Abstractions\AnoCore.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Runtime\AnoCore.Runtime.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Management.Host\AnoCore.Management.Host.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Modules.AnoVeto\AnoCore.Modules.AnoVeto.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Modules.Admin\AnoCore.Modules.Admin.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Modules.Stats\AnoCore.Modules.Stats.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Modules.Progression\AnoCore.Modules.Progression.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Modules.Tournament\AnoCore.Modules.Tournament.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Modules.Progression.Persistence\AnoCore.Modules.Progression.Persistence.csproj" />
    <ProjectReference Include="..\..\src\AnoCore.Modules.Tournament.Persistence\AnoCore.Modules.Tournament.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../examples/server-profiles/anomeme/*.json" Link="server-profile/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
