<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AnoCore</AssemblyName>
    <RootNamespace>AnoCore.Plugin</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnoCore.Runtime\AnoCore.Runtime.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.Admin\AnoCore.Modules.Admin.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.AnoVeto\AnoCore.Modules.AnoVeto.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
