<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AnoCore</AssemblyName>
    <RootNamespace>AnoCore.Plugin</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnoCore.Runtime\AnoCore.Runtime.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.Admin\AnoCore.Modules.Admin.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.Stats\AnoCore.Modules.Stats.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.Progression\AnoCore.Modules.Progression.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.Progression.Persistence\AnoCore.Modules.Progression.Persistence.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.AnoVeto\AnoCore.Modules.AnoVeto.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.Tournament\AnoCore.Modules.Tournament.csproj" />
    <ProjectReference Include="..\AnoCore.Modules.Tournament.Persistence\AnoCore.Modules.Tournament.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
